# Generated by Django 4.1.5 on 2023-01-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('editora', models.CharField(max_length=50)),
                ('foto', models.URLField(null=True)),
                ('autores', models.CharField(max_length=100)),
            ],
        ),
    ]
