# Generated by Django 4.1.5 on 2023-01-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obras',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
