# Generated by Django 4.1.5 on 2023-01-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_obras_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obras',
            name='foto',
            field=models.URLField(null=True),
        ),
    ]
